name: Go Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
          cache: true

      - name: Build all packages
        run: go build ./...

      - name: Run tests
        run: go test -v -failfast ./...

      - name: Build geth for Linux
        run: GOOS=linux GOARCH=amd64 go build -o geth-linux ./cmd/geth

      - name: Build geth for macOS (amd64)
        run: GOOS=darwin GOARCH=amd64 go build -o geth-darwin-amd64 ./cmd/geth

      - name: Build geth for macOS (arm64)
        run: GOOS=darwin GOARCH=arm64 go build -o geth-darwin-arm64 ./cmd/geth

      - name: Build geth for Windows
        run: GOOS=windows GOARCH=amd64 go build -o geth-windows.exe ./cmd/geth

      - name: Upload all geth binaries
        uses: actions/upload-artifact@v4
        with:
          name: geth-binaries
          path: |
            geth-linux
            geth-darwin-amd64
            geth-darwin-arm64
            geth-windows.exe
