name: Go Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
          cache: true

      - name: Build all packages
        run: go build ./...

      - name: Run tests
        run: go test -v -failfast ./...

      - name: Build inso for Linux
        run: GOOS=linux GOARCH=amd64 go build -o inso-linux ./cmd/geth

      - name: Build indo for macOS (amd64)
        run: GOOS=darwin GOARCH=amd64 go build -o inso-darwin-amd64 ./cmd/geth

      - name: Build inso for macOS (arm64)
        run: GOOS=darwin GOARCH=arm64 go build -o inso-darwin-arm64 ./cmd/geth

      - name: Build inso for Windows
        run: GOOS=windows GOARCH=amd64 go build -o inso-windows.exe ./cmd/geth

      - name: Upload all inso binaries
        uses: actions/upload-artifact@v4
        with:
          name: inso-binaries
          path: |
            inso-linux
            inso-darwin-amd64
            inso-darwin-arm64
            inso-windows.exe
