services:
  node1:
    image: flatgas-node
    container_name: flatgas-node1
    volumes:
      - ./keys/nodekey:/app/keys/nodekey:ro
      - ./docker-data/node1:/app/data
      - ./genesis.json:/app/genesis.json:ro
      - ./scripts/entrypoint-node1.sh:/app/entrypoint.sh:ro
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    entrypoint: ["sh", "/app/entrypoint.sh"]

  node2:
    image: flatgas-node
    container_name: flatgas-node2
    depends_on:
      - node1
    volumes:
      - ./keys/nodekey:/app/keys/nodekey:ro
      - ./docker-data/node2:/app/data
      - ./scripts/entrypoint-node2.sh:/app/entrypoint.sh:ro
    ports:
      - "8547:8545"
      - "8548:8546"
      - "30304:30303"
      - "30304:30303/udp"
    entrypoint: ["sh", "/app/entrypoint.sh"]
