services:
  node1:
    image: flatgas-node
    container_name: flatgas-node1
    volumes:
      - ./keys/nodekey:/app/keys/nodekey:ro
      - ./docker-data/node1:/app/data
      - ./genesis.json:/app/genesis.json:ro
      - ./scripts/entrypoint-node1.sh:/app/entrypoint.sh:ro
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    entrypoint: ["sh", "/app/entrypoint.sh"]
